# Site settings
title: Learn Rstats
email: wabarr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Learn R for statistics, data visualization, and data science.
baseurl: "/test" # the subpath of your site, e.g. /blog/
url: "http://wabarr.github.io/" # the base hostname & protocol for your site
twitter_username: wabarree
github_username:  wabarr
avatar : images/avatar.png
tagline: Learn stats with R...fast!
