# Site settings
title: Learn Rstats
email: wabarr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Lear
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4321" # the base hostname & protocol for your site
twitter_username: wabarree
github_username:  wabarr
avatar : images/avatar.png
tagline: Learn stats with R...fast!
highlighter: rouge

# Build settings
markdown: kramdown

